# Generated by Django 5.2 on 2026-08-29 21:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kiberclub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayMessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateField(auto_now_add=True)),
                ('year_of_birthday_message', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1984)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kiberclub.client', verbose_name='Связь с ребенком')),
            ],
            options={
                'verbose_name': 'Поздравление с днем рождения',
                'verbose_name_plural': 'Поздравления с днем рождения',
                'constraints': [models.UniqueConstraint(fields=('client', 'year_of_birthday_message'), name='unique_year_birthday_message')],
            },
        ),
    ]
