# Generated by Django 5.2 on 2026-08-30 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kiberclub', '0002_birthdaymessagestatus'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='birthdaymessagestatus',
            name='unique_year_birthday_message',
        ),
        migrations.RenameField(
            model_name='birthdaymessagestatus',
            old_name='year_of_birthday_message',
            new_name='year_of_future_birthday_message',
        ),
        migrations.AlterField(
            model_name='birthdaymessagestatus',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_messages', to='app_kiberclub.client', verbose_name='Связь с ребенком'),
        ),
        migrations.AddConstraint(
            model_name='birthdaymessagestatus',
            constraint=models.UniqueConstraint(fields=('client', 'year_of_future_birthday_message'), name='unique_year_future_birthday_message'),
        ),
    ]
